### ISSUE TITLE
Version 1.6.0 error

### ISSUE THREAD

**Issue by georgeoancea9** [soundar24/roundSlider#104]
I tried using version 1.6.0 and when calling
```const fn1 = $.fn.roundSlider.prototype._setProperties;```
I was getting `TypeError` - cannot read property `prototype` of `undefined`.
After going back to version 1.5.2 everything worked fine. 

Have you encountered this issue with this version so far? 
Thanks

**Comment by soundar24** [comment]
@georgeoancea9 I can't reproduce the mentioned issue. In one of the previous sample I just replaced the current version, where the same `_setProperties ` got overwritten.
https://jsfiddle.net/soundar24/8pgo9ce7/1/

Can you help me to reproduce your issue? do you have any specific environment or framework?

**Comment by soundar24** [comment]
@georgeoancea9 any update on this issue?

The major change on this version is [here](https://github.com/soundar24/roundSlider/commit/e5ed93c928b0fdfb971bc8672a639e29a79ad6f4#diff-d97ea4c3efed78626f1502b010ff3afeL6), previously the plugin uses the global jQuery object. now, if you are integrated the plugin through CDN or script tag then only it will uses the global jQuery object, otherwise it will uses the jQuery from the packages.

So the major possibility for your issue is, previously you might import the plugin from package and added a jquery cdn. So the plugin will be register with global jquery and the customization also done globally. Now replacing with new version will register with the jquery from the packages, so it won't available in your global jquery.

If this is your issue then we can handle this in the application level simply. Otherwise can you give some more details to get this issue.
