### ISSUE TITLE
Prevent returning to slider min val on continued drag rotation

### ISSUE THREAD

**Issue by jonnyfishman** [soundar24/roundSlider#105]
Currently when dragging the slider you can continue past the max point back to the minimum values. I can stop this from happening by calling this._handleUp() when the change slider value reaches the options.max value but this feels like a very clunky way of doing it especially as, when dragging quickly, this value can be skipped over and you need to release and re-initialise the drag if you want to reduce the value again.

Could you point me towards a more elegant way of implementing this behavior?
Thanks.

**Comment by soundar24** [comment]
@jonnyfishman are you expecting to prevent the handle after the max limit, without going to the min value during the rotation?

Check the below demo, here you can control the handle prevention by adjusting the `_handleDragDistance` value.
### https://jsfiddle.net/soundar24/1n87Lh6e/

Confirm me whether this is your expected behaviour? In the next release I will make this as a public property.

**Comment by jonnyfishman** [comment]
Amazing, that's it exactly!

I'd seen the d variable in _checkAngle but never thought to give it a value. 

Thanks again,
Jon
