### ISSUE TITLE
Positioning of slider tracks faulty?

### ISSUE THREAD

**Issue by wvhn** [soundar24/roundSlider#107]
Hi,
thanks for the great tool! 
I ran into a problem with some circleshapes, when I use ticks and labels around the tracks. The positioning of tracks / labels is not always as it should be:
![grafik](https://user-images.githubusercontent.com/17801971/102880221-46715300-444b-11eb-99f6-90c59bcadc40.png)

Then I found out that the behaviour changes with the line caps. If I use "butt" the layout is OK.
![grafik](https://user-images.githubusercontent.com/17801971/102880502-b54eac00-444b-11eb-9a28-3ab3ffaccad1.png)

Obviously, this is being caused by a value "extraSize" in the plugin which should correct for the additional space needed for the line caps but seems to misposition the tracks in certain cases.

**Comment by soundar24** [comment]
@wvhn Great stuff...

I believe you are using the custom track and number generation logic that I shared somewhere in the demos... If so, we can modify the logic a little bit to resolve this issue..

```
    // ### Fix for slider tracks misalignment
    var extraSize = 0,
      circleShape = o.circleShape;
    var isFullCircle = (circleShape == "full" || circleShape == "pie" || circleShape.indexOf("custom") === 0);
    if (o.svgMode && !isFullCircle) {
      if (o.lineCap != "none") {
        extraSize = (o.lineCap === "butt") ? (o.borderWidth / 2) : ((o.width / 2) + o.borderWidth);
        if (circleShape.indexOf("bottom") != -1) {
          numberTag.css("margin-top", extraSize + 'px');
        }
        if (circleShape.indexOf("right") != -1) {
          numberTag.css("margin-right", -extraSize + 'px');
        }
      }
    }
    // ### --
```

Here I have updated the demo for the fix:
### https://jsfiddle.net/soundar24/d5yntxvu/

Suppose if you are using different logic, or any other custom code then share your code in the jsFiddle so that I can provide the solution for that. Just check this and update me your comments...

**Comment by wvhn** [comment]
@soundar24 
Your solution works well for me. Thanks again !

![grafik](https://user-images.githubusercontent.com/17801971/103136653-75ddc500-46c2-11eb-9517-d0b11b1f1d1b.png)
