### ISSUE TITLE
is a double slider feasible?

### ISSUE THREAD

**Issue by wvhn** [soundar24/roundSlider#108]
Hi @soundar24 ,

we created a double slider for a room temperature controller by just putting two rundsliders into html-divs and position these via the margin attributes. This is a bit tricky and some areas of the paths are covered by other elements so that clicking into the slider doesn't work everywhere (dragging does).
![grafik](https://user-images.githubusercontent.com/17801971/103359108-9093ad80-4ab7-11eb-97c0-d3afd11040d7.png)

Is it possible to create a double slider within the plugin?

Regards 
wvhn

**Comment by soundar24** [comment]
@wvhn yes, by default round slider will work based on the element where clicked. So while place multiple sliders on top of other, this kind of problem ll happen.. so instead of taking the click element, based on the click position we can identify the corresponding slider..

To handle this logic I done a small workaround, check the below demo:
### https://jsfiddle.net/soundar24/254geobt/

When this nested slider support was added in the source by built-in at that time this can be handled internally, until then we can handle this in the application level.

Please check this and let me know your comments...

**Comment by wvhn** [comment]
Thanks again. Works fine for me. I inserted z-index for each layer in order to better control availability for user interaction.
