### ISSUE TITLE
Slider does not show on mobile devices

### ISSUE THREAD

**Issue by WesleyWas** [soundar24/roundSlider#121]
Hi everyone,

I am experiencing an issue with the Round Slider.
It does not show on mobile devices. I thought it may be because of the keyboard shortcuts or any config I don't properly set up.

Has anyone already experienced this issue ?

Thanks

**Comment by soundar24** [comment]
@WesleyWas actually there is no specific setup for mobile devices, if it works in web browsers then the same will be displayed in Mobile as well.

Suppose if you are facing issue then it might be due to any CSS media queries. Based on the screen resolution some content might be hide. Can you please share any of your demo site where you are facing the issue, so that I can identify the problem and help you to resolve. Thanks.
