### ISSUE TITLE
Gradient background for roundSlider with circleShape: pie and svgMode: true

### ISSUE THREAD

**Issue by Iam-Jesse** [soundar24/roundSlider#126]
Hello soundar24,

Thank you for this awesome library. 
Please how can I set a conical gradient for the background of the slider with options - circleShape: pie and svgMode: true?

![image](https://user-images.githubusercontent.com/35150300/236182862-fac0acdb-b7f0-481d-b7ef-c062738531e7.png)

The range slider below is a roundSlider instance, I want the background to be as the one above it.

**Comment by soundar24** [comment]
@Iam-Jesse can you please clarify me whether in the image both are roundSlider, or the first one is some other component. If so can you share me how you achieved that gradient effect, since it seems not the Conic Gradient and it looks like a linear gradient.

By default SVG doesn't support Conic Gradient but we have to achieve that through any customization only. So it wold be better to share any clear picture of your requirement, and the start and stop color of the Conic Gradient.

**Comment by Iam-Jesse** [comment]
Thank you for your reply soundar,

The first slider in the image is just a picture, the one below is a roundSlider instance. 

Can you help me customize it with this gradient - linear-gradient(95.75deg, #8A68A9 3.57%, #E49231 79.71%), please?

Thank you.

**Comment by soundar24** [comment]
You can refer the below sample which might satisfy your requirement. Here you can change the gradient color  by adjusting the stop color values.

## https://jsfiddle.net/soundar24/svtm8xhq/

In addition refer the below sample as well for reference:

### https://jsfiddle.net/soundar24/fbz826rc/

**Comment by Iam-Jesse** [comment]
Thank you soundar
