### ISSUE TITLE
roundSlider value can go from 0 to 100 instantly

### ISSUE THREAD

**Issue by Iam-Jesse** [soundar24/roundSlider#127]
Hello @soundar24 ,

I noticed that for a roundSlider with option {circleShape: pie}, the value can go from 0 to 100 instantly without progressing properly, if you drag through the space on the pie.

Example link: https://near-sg.webflow.io/#slider

![image](https://user-images.githubusercontent.com/35150300/236343929-e7cc0de7-d170-48eb-93a1-4d0f89b9aded.png)

**Comment by soundar24** [comment]
@Iam-Jesse yes, this is the actual behaviour in this case. Do you have any expected behaviour? In general we won't animate the handle during the drag, when you click on the path at that time only the smooth animation will happens.

If you have any particular requirement on this then just eloborate with details, and please re-open this.
