### ISSUE TITLE
The change animation is buggy

### ISSUE THREAD

**Issue by rolandschuetz** [soundar24/roundSlider#15]
Sometimes when I click somewhere and the animation from one point to another point starts there is a "second" animation as a side effect.
http://screencast.com/t/G3LFrhyTJ

This bug can be reproduced with the playground, tested on Chrome.

**Comment by soundar24** [comment]
Yes Roland, I already considered this. 

This is due to, currently the slider uses two half circles so that these overlaps occur. To solve this i have panned to add an SVG to form a single element, so that we can solve this.

For a rough sketch of feature plan, please check this demo:
http://jsfiddle.net/soundar24/LpuLe9tr/209/
This is just for your reference, still i need to validate some cases and will include in the source soon.

**Comment by rolandschuetz** [comment]
Well, if you don't animate the opacity change and only rotate for the animation it should also work with the current html elements.
But I only briefly looked at the code.

**Comment by soundar24** [comment]
updated demo:
https://jsfiddle.net/soundar24/1usqdvc9/5/

reference #12

**Comment by Aditya94A** [comment]
Any updates on this? Still not fixed 😕

**Comment by soundar24** [comment]
sorry, actually all the works was done already and I supposed to be release this in the last month itself. Hopefully I will merge those changes and bump the version in this weekend. Thanks

**Comment by soundar24** [comment]
@rolandschuetz @AdityaAnand1 finally I released the **roundSlider** next version **1.4.0** with the SVG mode support. so now all the issues ll be resolved (transparent background, animation issue), also you can do lot of customization.

Here I just updated a simple demo, please check and let me know your comments.

### https://jsfiddle.net/soundar24/n8wd79mb/

**Comment by Aditya94A** [comment]
Awesome! Nice work @soundar24 😁
