### ISSUE TITLE
roundSlider problem when setting a value programmatically

### ISSUE THREAD

**Issue by rolandschuetz** [soundar24/roundSlider#18]
I have problems setting the value programmatically. 

The idea here is that we have a fixed maximum of 10, but depending on some other input values the allowed maximum might only be 8. We are simulating this is a simple function attached to the change even.

The bug can be created by setting moving the handle to 8 twice. The second time no change event is triggered and the handle doesn't snap back.

Here is a demo:
http://codepen.io/rolandschuetz/pen/PZmqwZ?editors=101

**Comment by soundar24** [comment]
Yes, i can identify your issue. This is due to a minor mistake in the source. I will consider this fix in the next version.

Upto that you can use a simple workaround to solve this. I have added a single line in the sample to resolve this issue. Check the below updated demo:
http://codepen.io/soundar24/pen/MKmabM?editors=100

In the demo I just added the below line:

```
this._prechange = this.options.value;
```

Hope it helps you.

**Comment by rolandschuetz** [comment]
Thanks, that's perfect!

**Comment by soundar24** [comment]
The reported issue was solved in version 1.2, Please check the updated demo:
http://codepen.io/soundar24/pen/WrMLGp?editors=0010
