### ISSUE TITLE
Smooth animation regardless the step

### ISSUE THREAD

**Issue by zipper** [soundar24/roundSlider#39]
Currently, when we use low max value with `step: 1` in settings (like `min: 0, max: 4, step: 1`), the handle movement when dragged is not smooth, the handle bar "jumps" from 0° to 90°. It would be great if the handle could be dragged smoothly (like if the max was set to 360) and "rounded" to closest value when dropped. Equally, the click on lets say 60° mark would result in rounded value of 1 (90°). I hope you understand what I mean :)

**Comment by zipper** [comment]
Oh, nevermind, I found it's duplicate with #21.

**Comment by soundar24** [comment]
ya you are right.. in the mentioned bug i already provided the workaround also to handle this.. soon i will include this as a option in source level.. :)

**Comment by zipper** [comment]
Thank you. Also, in my project, I need a conical gradient as range background. I managed to simulate it in your mentioned example with few changes - obviously the CSS and also little tweak in JS (stroke dash offset change is negative number), see http://jsfiddle.net/8qc8Lzwm/1/. I'm not sure if there is any better solution to this or how the browser support would be, but it would be very useful to be able to use gradients as range background as well.

Feel free to create a new issue or just dismiss the idea :)

**Comment by soundar24** [comment]
The current example was really great..
Still i am little bit confused with your requirement (conical gradient).. can you let me know what is your exact goal ? If possible you can share any screenshot or reference links.

You can contact me through here:
http://roundsliderui.com/contactme.html

[Tomorrow i will reply you, since it almost late night here :night_with_stars: :) ]
