### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by Hydro8** [soundar24/roundSlider#69]
Hi

I try to use roundslider inside bootstrap column but the size doesn't match the column width.

For example, on mobile : [https://img4.hostingpics.net/pics/548215screenshot19216815020170615083757.png](https://img4.hostingpics.net/pics/548215screenshot19216815020170615083757.png)

Do you an idea how to have roundslider adapt to column width ?

Thank

**Comment by soundar24** [comment]
@Hydro8 , do you have any live demo sample to reproduce this issue ?

I can understand the issue, but i can't make a similar sample with bootstrap. So if you provide any demo sample or demo link then I will resolve the issue with that and update you..

Thanks.. :)

**Comment by Hydro8** [comment]
Here a sample from home 

http://88.182.191.233:8090/reddit/

You can see my issue when you switch to mobile view, roundslidder doesn't fit the column.

**Comment by soundar24** [comment]
Actually, the bootstrap column was resized to different dimension based on the screen resolution, so that the roundSlider inside the column was not adaptable.

To make it as responsive you need to write the dimension related style in media query, otherwise you can handle in the window resize event. I think the second was suitable for this case.

Based on that I have prepared the below code:
```
$(window).resize(function() {
	setTimeout(function() {
		var parent = slider.control.parent();
		var height = parent.height() - 80; 
		// 80 is the height of two rows placed next to the slider
		var width = parent.width();
		var radius = parseInt(height > width ? width : height) / 2;
		slider.option("radius", radius);
	}, 300);
});
```
Place the above code in your application. In addition, remove the fixed height `height: 380px !important;` from the CSS style and add the `margin: 0 auto;` style. So it becomes,
```
#slider {
    overflow: hidden;
    margin: 0 auto;
}
```

Now check your application, it will work in all resolutions and cases.

**Comment by Hydro8** [comment]
It work great when I resize my windows, however when I load the page on my phone, the slider isn't fit the column, I need to resize it to finally fit the column.

**Comment by soundar24** [comment]
Initial time you have set the static radius, but the container will render based on the resolution, this is the problem here.. So you may be set the generic value for the radius, otherwise you can change the radius value in the `beforeCreate` event based on that parent container.

So, in your application the code becomes like this:

```
$("#slider").roundSlider({
    handleShape: "round",
    width: 65,
    radius: "208",
    circleShape: "pie",
    startAngle: 315,
    min: "16",
    max: 32,
    showTooltip: false,
    handleSize: "65,10",
    beforeCreate: function () {
        this.options.radius = this.control.parent().width() / 2;
    },
    create: function () {
        this._createHandle(2).addClass("gray rs-disable").parent().addClass("rs-custom");
    }, 
    drag: "valChange",
    change: "valChange"
});
```

**Comment by Hydro8** [comment]
It works great ! Thank you !

Do you know how to "refresh" roundSlider after ajax call for example ?

**Comment by soundar24** [comment]
Need to "refresh" the roundSlider means what you need to do ? In ajax call you will get any value in the success function, so you can apply that value dynamically to roundSlider. Even you can update any property dynamically.

So, let me know what do you mean about 'refresh', what functionality you want to consider here ?

**Comment by Hydro8** [comment]
I don't achieve to reproduce the problem for the moment. 

Thank a lot for your help !
