### ISSUE TITLE
Update jsDelivr links

### ISSUE THREAD

**Issue by LukasDrgon** [soundar24/roundSlider#73]
[jsDelivr switched to a fully automated system](https://www.jsdelivr.com/features), that can serve files from npm and GitHub. This means all future releases will be available automatically, but will use a new link structure.

I noticed that there are old links at http://roundsliderui.com/document.html#how-to-install, the correct links are: https://cdn.jsdelivr.net/npm/jquery@1.11.3/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/round-slider@1.3/dist/roundslider.min.css
https://cdn.jsdelivr.net/npm/round-slider@1.3/dist/roundslider.min.js.

You can find links for all files at https://www.jsdelivr.com/package/npm/round-slider.

Feel free to ping me if you have any questions regarding this change.

**Comment by soundar24** [comment]
Thanks @LukasDrgon .. Is this the standard format of jsDelivr?  So, can you please confirm that the [old links](https://cdn.jsdelivr.net/jquery.roundslider/1.3/roundslider.min.js) will works in future or not, since all the jsFiddle demo samples used the old syntax only..

Also in future release, is the old format CDN links will works?

**Comment by MartinKolarik** [comment]
@soundar24 all the old links will continue to work, but you'll have to use the new format for all versions published later than in May 2017 (for older versions, either format will work). We recommend everyone to update their docs to the new links immediately, so that you don't forget to do it when you release a new version.

**Comment by soundar24** [comment]
Updated the [documents](http://roundsliderui.com/document.html#how-to-install) @MartinKolarik 👍

**Comment by MartinKolarik** [comment]
👍
