### ISSUE TITLE
Unable to select max value using slider

### ISSUE THREAD

**Issue by davidhill001** [soundar24/roundSlider#79]
When setting the min value as 0 and the max value as 359, it is impossible to select 359 using the slider wheel using mouse drag, it only goes up to 358.

The only way I can select 359 is to type 359 in the box in the middle of the slider or use the mouse wheel.

I am using the latest Chrome on a Mac and this is the example I am using:

```
$("#colourwheel").roundSlider({
                        radius: 80,
                        width: 8,
                        handleSize: "34,10",
                        sliderType: "default",
                        mouseScrollAction: true,
                        min: 0,
                        max: 359,
                        value: 30
                    });
```

**Comment by soundar24** [comment]
Actually the reason for this is, the circle's start angle is 0 and end angle is 360. where both start and end angle lies on the same place, so the movement between these 2 points are very minute. So I suggest you use the end angle as "359", so each value having each degree now instead of colliding 0 and 359 in the same place.

Check the below demo and let me know your comments:
http://jsfiddle.net/soundar24/s5gpugjn/7/

In addition, if you want to prevent the immediate movement between start and end then you can customer like below:
http://jsfiddle.net/soundar24/s5gpugjn/8/

**Comment by davidhill001** [comment]
I have added the endAngle option with the value "+359" as you suggested and it is working perfectly now, thank you very much for your help.
