### ISSUE TITLE
strange border with rangeColor

### ISSUE THREAD

**Issue by shalamos** [soundar24/roundSlider#97]
Hi, thanks for this great plugin. 

When I set a rs-path-color and a rs-track-color, you can see a bit of the range-color at the left side of the Track. Is there any way to fix this? 

I use Chrome 76.0.3809.100 on macOS 10.13.6 with a Retina Display.  

![image](https://user-images.githubusercontent.com/710494/64122874-1a881500-cda3-11e9-9258-655a57877a61.png)

**Comment by soundar24** [comment]
Actually the current implementation of roundSlider uses the div elements, so that you are facing these UI issues.

I already provided support for the SVG version, but still didn't include in the source. So I have provided that code as a sample level that will solve your issue.

Check the below demo:
## https://jsfiddle.net/soundar24/se6hauLw/3/

![image](https://user-images.githubusercontent.com/8916666/64287225-c173d900-cf7c-11e9-95da-0d2db2269ce3.png)

**Comment by shalamos** [comment]
Yes, it seems like those divs do not overlap perfectly. The svg version works great for me, thanks a lot! Do you have any plans on releasing it?

**Comment by soundar24** [comment]
I already have the plan from a long time, but don't have the time. Also I hope that people got satisfied with this workaround, so that not focused on this.

However please let me know your priority, based on that I will try to release this in a couple of weeks or at-least in a month.

**Comment by shalamos** [comment]
Yes, I can use the workaround for now, but if you release it I will switch to that for sure. Thanks again!

**Comment by soundar24** [comment]
@shalamos I forget to update you, roundSlider was released with SVG mode on January itself. Please check the below demo:
### https://jsfiddle.net/soundar24/r5jcb1q4/1/

You can simply migrate to the latest version and let me know if you faced any issues.. Thanks...
